version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "8081:8081"
      - "6831:6831"
    environment:
      - JAEGER_AGENT_HOST=host.docker.internal
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - prometheus
    networks:
      - microservices

  payment:
    build: ./payment
    ports:
      - "8082:8082"
    environment:
      - JAEGER_AGENT_HOST=host.docker.internal
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - prometheus
    networks:
      - microservices

  order:
    build: ./order
    ports:
      - "8083:8083"
    environment:
      - JAEGER_AGENT_HOST=host.docker.internal
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - prometheus
    networks:
      - microservices

  notification:
    build: ./notification
    ports:
      - "8084:8084"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - prometheus
    networks:
      - microservices


  web:
    build: ./web
    ports:
      - "8080:8080"
    networks:
      - microservices


  prometheus:
    image: docker.io/prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.29
    environment:
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "16685:16685"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge