global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8081']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:8082']

  - job_name: 'order'
    static_configs:
      - targets: ['order:8083']

  - job_name: 'notification'
    static_configs:
      - targets: ['notification:8084']